version: '2.4'
services:
  db:
    image: postgres:15
    restart: always
    # command: start-single-node --insecure
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"

  ingest:
    depends_on:
      - db
    restart: on-failure
    image: subsquid/substrate-ingest:firesquid
    volumes:
      - "../../src/typesBundle.json:/configs/typesBundle.json"
    command: [
       "-e", "${NODE_NAME}",
       "-c", "5",
       "--out", "${DATABASE_URL}",
       "--types-bundle", "/configs/typesBundle.json",
       "--write-batch-size", "10"
    ]

  gateway:
    depends_on:
      - db
    image: subsquid/substrate-gateway:firesquid
    environment:
      RUST_LOG: "substrate_gateway=info,actix_server=info"
    command: [
       "--database-url", "${DATABASE_URL}",
       "--database-max-connections", "100",
       "--scan-start-value", "1",
       "--scan-max-value", "10000",
    ]
    ports:
      - "8000:8000"

  explorer:
    image: subsquid/substrate-explorer:firesquid
    environment:
      DATABASE_TYPE: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USERNAME}
      DATABASE_PASS: ${DATABASE_PASS}
    ports:
      - "3000:3000"