name: archive-prod
services:
  db:
    image: cockroachdb/cockroach:v22.2.6 # CockroachDB cluster might be a better fit for production deployment
    restart: always
    command: start-single-node --insecure
    volumes:
      - "${PWD}/archive/prod/cockroach-data/crdb:/cockroach/cockroach-data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: squid-archive-prod
      
    ports:
     - "26257:26257"
     - "8080:8080"

  ingest:
    depends_on:
      - db
    restart: on-failure
    image: subsquid/substrate-ingest:firesquid
    volumes:
      - "../../src/typesBundle.json:/configs/typesBundle.json"
    command: [
       "-e", "wss://ws.framenode-1.r0.dev.sora2.soramitsu.co.jp",
       "-c", "5", # allow up to 20 pending requests for the above endpoint (default is 5)
       #  "--start-block", "1000000",
      "--out", "${DATABASE_URL}",
       "--types-bundle", "/configs/typesBundle.json",
       "--write-batch-size", "10"
    ]

  gateway:
    depends_on:
      - db
    image: subsquid/substrate-gateway:firesquid
    environment:
      RUST_LOG: "substrate_gateway=info,actix_server=info"
    command: [
       "--database-url", "${DATABASE_URL}",
       "--database-max-connections", "100", # max number of concurrent database connections
       # "--evm-support" # uncomment for chains with Frontier EVM pallet
                         # (e.g. Moonbeam/Moonriver or Astar/Shiden)
       "--scan-start-value", "1",
       "--scan-max-value", "10000",
    ]
    ports:
      - "8888:8000"

  # Explorer service is optional.
  # It provides rich GraphQL API for querying archived data.
  # Many developers find it very useful for exploration and debugging.
  explorer:
    image: subsquid/substrate-explorer:firesquid
    environment:
      DB_TYPE: cockroach # set to `cockroach` for Cockroach DB
      DB_HOST: db
      DB_PORT: "26257"
      DB_NAME: "defaultdb"
      DB_USER: "root"
      DB_PASS: ""
    ports:
      - "4444:3000"
