export const calls = [
	'*',
	'Assets.register',
    'Assets.transfer',
    'LiquidityProxy.swap',
    'LiquidityProxy.swap_transfer',
	'LiquidityProxy.swap_transfer_batch',
    'PoolXYK.deposit_liquidity',
    'PoolXYK.withdraw_liquidity',
    'IrohaMigration.migrate',
    'Utility.batch_all',
    'EthBridge.transfer_to_sidechain',
    'PswapDistribution.claim_incentive',
    'Rewards.claim',
    'VestedRewards.claim_rewards',
    'VestedRewards.claim_crowdloan_rewards',
    'Referrals.set_referrer',
    'Referrals.reserve',
    'Referrals.unreserve',
    'DemeterFarmingPlatform.deposit',
    'DemeterFarmingPlatform.withdraw',
    'DemeterFarmingPlatform.get_rewards',
	'BridgeMultisig.as_multi',
	'BridgeMultisig.as_multi_threshold_1',
] as const


export const events = [
	'*',
	'EthBridge.IncomingRequestFinalized',
    'EthBridge.IncomingRequestFinalizationFailed',
    'EthBridge.RequestRegistered',
    'Tokens.Deposited',
    'Tokens.Withdrawn',
    'Tokens.Transfer',
	'TransactionPayment.TransactionFeePaid',
    'Balances.Deposit',
    'Balances.Deposited',
    'Balances.Withdraw',
    'Balances.Transfer',
    'Currencies.Transferred',
    'Currencies.Deposited',
    'XorFee.FeeWithdrawn',
    'XorFee.ReferrerRewarded',
    'Assets.AssetRegistered',
    'Assets.Transfer',
    'LiquidityProxy.Exchange',
	'LiquidityProxy.BatchSwapExecuted',
    'DemeterFarmingPlatform.Deposited',
    'DemeterFarmingPlatform.RewardWithdrawn',
    'DemeterFarmingPlatform.Withdrawn',
	'XstPool.SyntheticAssetEnabled',
	'Band.SymbolsRelayed',
	'Staking.Rewarded'
] as const